plugins {
    id 'java'
}

group = 'org.gtfd'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation("org.ow2.asm:asm:9.9")
    implementation('org.ow2.asm:asm-tree:9.9')
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}

test {
    useJUnitPlatform()
}

sourceSets {
    server {
        java {
            srcDirs = ['src/server/java']
        }
    }
}

task buildServerJar(type: Jar) {
    dependsOn compileServerJava
    archiveFileName = 'server.jar'
    from sourceSets.server.output.classesDirs
    manifest {
        attributes 'Main-Class': 'org.gtfd.server.Main'
    }
    destinationDirectory = file('src/main/resources')
}

processResources.dependsOn buildServerJar