plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation("org.ow2.asm:asm:9.9")
    implementation('org.ow2.asm:asm-tree:9.9')
}

test {
    useJUnitPlatform()
}